show databases;
create database microservices;
use microservices;
show tables;
desc user;
desc project;
select * from user;
select * from project;
select * from project where projectname="payback";
select * from project where userid=3;