server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: project-service
  main:
    allow-circular-references: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    instance:
      preferIpAddress: true
    service-url:
      defaultZone: http://localhost:8761/eureka/